### ISSUE TITLE
this.$moment().locale(lang) does not works

### ISSUE THREAD

**Issue by nioc** [brockpetrie/vue-moment#40]
Hello, I want to change locale with a user click event on button.

I have the following 
```` js
// main.js
import Vue from 'vue'
import VueMoment from 'vue-moment'
const moment = require('moment')
require('moment/locale/en-gb')
require('moment/locale/fr')
Vue.use(VueMoment, {
  moment
})
````
And then, using in component:
```` js
// app.vue
<script>
  methods: {
    setLanguage (lang) {
      console.log(lang)
      this.$moment().locale(lang)
      console.log(this.$moment().locale())
    }
  }
}
</script>
````

When I call the function from the button, I got the following
````
setLanguage('en')
en
fr
````
````
setLanguage('fr')
fr
fr
````

Is it possible to update the moment locale this way?

**Comment by BrockReece** [comment]
I think this issue would be solved by PR #37

**Comment by BrockReece** [comment]
Hi @nioc,
We have now merged in PR #37, I believe this refactor will fix your issue.

```js
// app.vue
<script>
  methods: {
    setLanguage (lang) {
      console.log(lang)
      this.$moment.locale(lang)
      console.log(this.$moment.locale())
    }
  }
}
</script>
```

**Comment by nioc** [comment]
Hello, great news. I'll try it tonight or tomorrow. Stay tuned :)

**Comment by nioc** [comment]
I'm sorry but I think PR does not fix my issue :cry: 
I launched `npm update`, checked my package.json seems correct : `"vue-moment": "^2.1.0"`
I also tried to change the value `en` to `en-gb`, still do not change...

**Comment by BrockReece** [comment]
ok, so I think the ordering of the imports of the locales is important as it uses the last import as the default locale. If I want 'en-gb' as my default, but an option to use 'fr', I order my imports like this...

```js
import 'moment/locale/fr'
import 'moment/locale/en-gb'
```

This is the code I have put in my mounted method
```js
mounted() {
  console.log(this.$moment.locale())
  this.$moment.locale('fr')
  console.log(this.$moment.locale())
  this.$moment.locale('en-gb')
  console.log(this.$moment.locale())
},
```

Which outputs...
```
en-gb
fr
en-gb
```

Which is what I believe we are after?

**Comment by BrockReece** [comment]
I think this is fixed now

**Comment by pakping** [comment]
nuxt 
1
 import 'moment/locale/th'

2  
   moment(date) {
     // moment.locale('th');
       var strdate = moment("th").format("LLLL");
      var strdate = moment(date).add(543, "years");
      return moment(strdate).format("Do MMMM YYYY  hh:mm");
    },
